name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "40 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses:  Asgarrrrr/Weekly-Development-Breakdown@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: eb5182c2474e0177e0380a72fe9401f3
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
