name: Update gist with WakaTime stats
on:
  push:
    branches:
      - master
  schedule:
    - cron: "40 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses:  Asgarrrrr/Weekly-Development-Breakdown@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 435ac4d7542ff5e44ae45212f0d020b4
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
